# Generated by Django 6.0.4 on 2026-05-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_sociallink'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallink',
            name='custom_icon_svg',
            field=models.TextField(blank=True, help_text='Paste raw SVG code here if not using Iconify'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='icon',
            field=models.CharField(blank=True, help_text='Iconify icon name e.g. logos:facebook, mdi:telegram', max_length=100),
        ),
    ]
