# Generated by Django 6.0.4 on 2026-05-08 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_sociallink_custom_icon_svg_alter_sociallink_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sociallink',
            name='icon',
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='custom_icon_svg',
            field=models.TextField(help_text='Paste raw SVG code here'),
        ),
    ]
