# Generated by Django 6.0.4 on 2026-05-08 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_sociallink_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetting',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='youtube_url',
        ),
    ]
